name: Assign reviewer to PR
on:
    pull_request:
        types: [opened]
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign PR'
              uses: pozil/auto-assign-issue@v1
              with:
                  abortIfPreviousAssignees: true
                  repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
                  teams: code-reviewers
                  numOfAssignee: 1
